# Generated by Django 4.1.5 on 2023-01-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=models.CharField(choices=[('NY', 'NY'), ('MA', 'MA')], default=0, max_length=2),
        ),
    ]
