# Generated by Django 4.1.3 on 2023-01-24 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_restaurant_address_restaurant_hours_restaurant_image_and_more'),
        ('main_app', '0002_user_restaurant_address_restaurant_hours_and_more'),
    ]

    operations = [
    ]
