# Generated by Django 4.1.3 on 2023-01-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_restaurant_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='comment',
            field=models.ManyToManyField(blank=True, to='main_app.comment'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=models.CharField(choices=[('NY', 'NY'), ('MA', 'MA')], default='NY', max_length=2),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='type',
            field=models.CharField(max_length=100, verbose_name='Cuisine'),
        ),
    ]
