# Generated by Django 4.1.5 on 2023-01-26 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_comment_comment_alter_restaurant_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='restaurant',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='main_app.restaurant'),
            preserve_default=False,
        ),
    ]
